var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/dashboard/mentor/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__083fqh8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0tkc711.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qshnir._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n9u3-h._.js")
R.c("server/chunks/ssr/_0q61nzo._.js")
R.c("server/chunks/ssr/src_lib_utils_ts_0cn8qfr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(dashboard)_layout_tsx_027owf8._.js")
R.c("server/chunks/ssr/src_app_(dashboard)_loading_tsx_0do9s3c._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_dashboard_mentor_page_actions_0ids5-b.js")
R.m(729199)
module.exports=R.m(729199).exports
