var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blogs/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12u_h3s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0frp~35.js")
R.c("server/chunks/ssr/_0wwa~ju._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_0g8jul2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qshnir._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n9u3-h._.js")
R.c("server/chunks/ssr/_0q61nzo._.js")
R.c("server/chunks/ssr/src_lib_utils_ts_0cn8qfr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_blogs_[id]_page_actions_0jda_k-.js")
R.m(586978)
module.exports=R.m(586978).exports
